# Generated by Django 4.2.1 on 2023-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='group',
            field=models.TextField(max_length=250, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='notes',
            field=models.TextField(max_length=250, verbose_name='Примітки'),
        ),
    ]
