# Generated by Django 4.1.5 on 2023-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Оцінка'),
        ),
    ]
