# Generated by Django 5.0.4 on 2024-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0002_alter_presentation_group_alter_presentation_notes'),
        ('maindb', '0002_presentation_rating'),
    ]

    operations = [
    ]
